name: Deploy Jekyll Site

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3 # or the version you need

      - name: Install dependencies
        run: bundle install

      - name: Build the site
        run: bundle exec jekyll build
        env:
          PROFILE_TOKEN: ${{ secrets.PROFILE_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
